INHERIT: active-handout.yml

site_name: Sistemas Hardware-Software BCC - 2026/1

extra:
  custom_variables:
    repo_aps: https://github.com/Insper/SistemasHardwareSoftwareBCC/
    repo_aps_git: https://github.com/Insper/SistemasHardwareSoftwareBCC.git

extra_javascript:
  - js/tabs.js
  - js/termynal.js
  - js/custom.js

extra_css:
    - css/termynal.css

nav:
  - 'Home': index.md
  - sobre.md
  - entregas.md
  - Aulas:
    - "01 - Inteiros na CPU": aulas/01-inteiros/index.md
    - "02 - Representação de dados em RAM": aulas/02-ram/index.md
    # - "03 - Arquitetura x86-64": aulas/03-arquitetura-x86/index.md
    # - "04 - Funções": aulas/04-funcoes-mov/index.md
    # - "05 - Condicionais": aulas/05-condicionais/index.md
    # - "06 - Condicionais e funções": aulas/06-condicionais-funcoes/index.md
    # - "07 - Loops": aulas/07-loops/index.md
    # - "08 - Variáveis locais": aulas/08-variaveis-locais/index.md
    # - "09 - Array em Assembly": aulas/09-arrays/index.md
    # - "10 - Revisão para a AI": aulas/10-revisao-AI/index.md
    # - "11 - Processos": aulas/11-processos/index.md
    # - "12 - Carregamento de programas": aulas/12-exec/index.md
    # - "13 - Entrada/Saída": aulas/13-entrada-saida/index.md
    # - "14 - Enviando sinais": aulas/14-sinais-I/index.md
    # - "15 - Capturando sinais": aulas/15-sinais-II/index.md
    # - "16 - Concorrência e Threads": aulas/16-threads-I/index.md
    # - "17 - Sincronização com Mutex": aulas/17-sincronizacao/index.md
    # - "18 - Semáforos": aulas/18-semaforos/index.md
    # - "19 - Semáforos II e Modelos de concorrência": aulas/19-semaforos-II/index.md
    # - "20 - Questões de revisão": aulas/20-questoes-de-revisao/index.md
  - Labs:
    - "Hackerlab": labs/hackerlab.md
    # - "Lab processos": labs/processos.md
    # - "Lab threads": labs/threads.md
  - Referências e links:
    - "Dicas e links": dicas/DicasLinks.md
    - "Configuração github": dicas/github.md
    - "Linux: Instalação e configuração": dicas/linux.md
